### ISSUE TITLE
Latest macOS release

### ISSUE THREAD

**Issue by golbiga** [mozkeeler/osclientcerts#11]
I was testing the module in 71 and ESR 68.3.0. In 71 it's working, but will only load the certs from a smartcard if you launch the application with a card/yubikey inserted. If you insert the card after launching the application, it will not load properly and requires a restart. As well if you remove the card, it seems to cache the certs, but they're no longer present.

In 68.3.0 it wont load the driver at all, not sure if the entitlement made it to ESR yet.

**Comment by mkaply** [comment]
@mozkeeler Any thoughts on this?

**Comment by mozkeeler** [comment]
Yes, this is probably something that should be made to work.

**Comment by mozkeeler** [comment]
@golbiga does trunk work for you now?

**Comment by golbiga** [comment]
I just tested in 73.0.1 and it would poll the card if it wasn't present when launching the app, which it wouldn't do in previous versions. I did notice its still caching the certs if the card is removed when the app is running. Not sure if this is an issue or not, but with other pkc11-shims it will clear out the certs if not present. Thanks for the update!

**Comment by mozkeeler** [comment]
Ok - thanks!
