### ISSUE TITLE
Support Android client certificates

### ISSUE THREAD

**Issue by jcjones** [mozkeeler/osclientcerts#13]
Since Fenix no longer supports importing certificates, `osclientcerts` is our best tool for Android.

**Comment by eranmes** [comment]
A few pointers for Android, which, I hope, would be helpful:
* KeyChain (https://developer.android.com/reference/android/security/KeyChain) is the class you're after.
* choosePrivateKeyAlias (https://developer.android.com/reference/android/security/KeyChain#choosePrivateKeyAlias(android.app.Activity,%20android.security.KeyChainAliasCallback,%20java.lang.String%5B%5D,%20java.security.Principal%5B%5D,%20java.lang.String,%20int,%20java.lang.String)) should be called to prompt the user to select an appropriate client certificate from the certs installed in the device's keychain (note that a valid list of issuers and key types should be passed in; those will narrow down the list of certs the user chooses from).
* The host and port arguments are also important - they are shown to the user as context.
* If choosePrivateKeyAlias returns null (via the callback) then there's no suitable cert or the user chose not to grant the site access to any certificate.
* Assuming choosePrivateKeyAlias returned with a non-empty string, getPrivateKey (https://developer.android.com/reference/android/security/KeyChain#getPrivateKey(android.content.Context,%20java.lang.String)) and getCertificateChain (https://developer.android.com/reference/android/security/KeyChain#getCertificateChain(android.content.Context,%20java.lang.String)) can be used to get the PrivateKey and Certificate[] objects respectively.
* All crypto operations should be done using Java's KeyStore API, utilizing obtained PrivateKey instance - there's no other stable public interface. The private keys cannot be exported for use outside of this API as they are hardware-backed and so crypto operations happen in the secure element (Keymaster HAL implementation, to be exact).

There's currently no way to programatically generate keys into KeyChain on consumer devices - if that's a feature Firefox plans to support at some point, let me know.

**Comment by mozkeeler** [comment]
This work will be done in Firefox, not this repo.
