### ISSUE TITLE
Caution regarding SecCertificateCopyNormalized functions

### ISSUE THREAD

**Issue by kenh** [mozkeeler/osclientcerts#14]
Hi,

I was curious about your module (since I wrote keychain-pkcs11) so I took a look at yours. I wanted to caution you about your use of SecCertificateCopyNormalizedIssuerSequence and SecCertificateCopyNormalizedISubjectSequence. The "normalized" DER output from those functions is NOT guaranteed to match the corresponding DER sequence in the original sequence (it appears, in my testing, that the fields in the subject and issuer are upper-cased). This caused me a huge amount of grief with Firefox because Firefox stores certificates in an internal hash table and when it went to search for certificates it would search based on the issuer or subject returned as part of the PKCS11 attributes, but it wouldn't be able to find the certificates because the "normalized" DER sequence didn't match the ACTUAL DER sequence from the certificate that was stored in the hash table. I lost a few days figuring that out, and I didn't want that to happen to anyone else.

**Comment by mozkeeler** [comment]
Thanks for letting us know! Sorry it took years to respond to this. At some point we moved away from those functions, and we don't use them in the version of osclientcerts that's in Firefox.
