### ISSUE TITLE
Issues loading certs on Smartcard (macOS)

### ISSUE THREAD

**Issue by golbiga** [mozkeeler/osclientcerts#9]
After building the module and adding it to security devices I'm able to view the certificates by clicking on View Certificates -> Your Certificates. The issue is when visiting a site that requires smartcard login I'm unable to choose the certs on my card. The certificate picker shows up but I'm unable to select any of the certs on my card.

**Comment by mozkeeler** [comment]
Thanks for trying this out! What version of MacOS are you on?

**Comment by golbiga** [comment]
macOS 10.15.1

**Comment by mozkeeler** [comment]
Thanks! This may be due to bug 1593041 (Firefox doesn't have the right "entitlement" to access smartcards). Can you try with a recent Nightly? https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by golbiga** [comment]
That worked! When does the entitlement change make it to mainline and ESR?

**Comment by mozkeeler** [comment]
Right now it's in 72, which is scheduled to be released in January. I'll see if we can uplift it.

**Comment by mozkeeler** [comment]
This is being handled in mozilla-central, so I'm going to close this.
